version: "3.5"
services:
  succubus.space:
    container_name: succubus.space
    build: 
        context: .
    restart: always
    ports: 
        - 4445:4445
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=dev
    depends_on:
      - redis

  redis:
    container_name: succubus.space-redis
    image: redislabs/rejson:latest
    restart: always
