version: "3.5"
services:
  succubus.space:
    container_name: succubus.space
    image: ghcr.io/turbocheetah/succubus.space-api:latest
    restart: always
    environment:
      - VIRTUAL_HOST=api.succubus.space
      - VIRTUAL_PORT=4445
      - LETSENCRYPT_HOST=api.succubus.space
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    container_name: succubus.space-redis
    image: redislabs/rejson:latest
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
