version: '3.5'
services:
    succubus.space:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: succubus.space
        restart: always
        ports:
           - '4445:4445'
        environment:
           - VIRTUAL_HOST=api.succubus.space
           - VIRTUAL_PORT=4445
           - LETSENCRYPT_HOST=api.succubus.space
           - PORT=4445
           - REDIS_HOST=redis
           - REDIS_PORT=6379
        depends_on:
           - redis

    redis:
        container_name: succubus.space-redis
        image: redislabs/rejson:latest
        restart: always

networks:
  default:
    external:
      name: nginx-proxy
