version: '3.7'

services:
  redis:
    image: redislabs/rejson:latest
    container_name: succubus.space-redis
    restart: 'unless-stopped'
    ports:
      - '6379:6379'

  mongo:
    image: mongo
    container_name: succubus.space-mongo
    restart: 'unless-stopped'
    ports:
      - '27017:27017'
