version: '3.7'

services:
  succubus.space-api:
    image: ghcr.io/turbocheetah/succubus.space-api:latest
    container_name: succubus.space-api
    ports:
      - '4445:4445'
    restart: 'unless-stopped'
    depends_on:
      - redis
      - mongo

  redis:
    image: redislabs/rejson:latest
    container_name: succubus.space-redis
    restart: 'unless-stopped'

  mongo:
    image: mongo
    container_name: succubus.space-mongo
    restart: 'unless-stopped'
    volumes:
      - mongo:/data/db

volumes:
  mongo: